from __future__ import annotations

import secrets
import shutil
from datetime import datetime
from pathlib import Path

from setup.cli import CLI, BOLD, CYAN, DIM, GREEN, RESET, YELLOW
from setup.modules import MODULES
from setup.rollback import Rollback
from setup.state import SetupState
from setup.wizard import run_wizard

ROOT = Path(__file__).parent.parent


def run() -> None:
    cli = CLI()
    state = SetupState()

    # ── Wizard ────────────────────────────────────────────────────────────────
    try:
        run_wizard(cli, state)
    except SystemExit:
        return

    # ── Summary ───────────────────────────────────────────────────────────────
    cli.section("SUMMARY")

    has_actions = False
    for mod in MODULES:
        actions = mod.plan(state)
        for action in actions:
            # Parse verb from "(VERB) description" format
            if action.startswith("("):
                end = action.index(")")
                verb = action[1:end]
                desc = action[end + 2:]
            else:
                verb, desc = "CONFIGURE", action

            color = {
                "ADD": GREEN,
                "CONFIGURE": CYAN,
                "KEEP": DIM,
                "REMOVE": YELLOW,
            }.get(verb, DIM)
            print(f"    {color}{verb:<12}{RESET} {desc}")
            has_actions = True

    if not has_actions:
        cli.info("No changes to apply.")
        return

    print()
    _show_env_summary(state, cli)

    print()
    if not cli.confirm("Apply these changes?", default=True):
        cli.info("Setup cancelled. No changes made.")
        return

    # ── Backup ────────────────────────────────────────────────────────────────
    rollback = Rollback()
    all_paths: list[Path] = []
    for mod in MODULES:
        all_paths.extend(mod.files_touched(state))

    # Deduplicate
    seen: set[Path] = set()
    unique_paths = [p for p in all_paths if not (p in seen or seen.add(p))]
    rollback.snapshot(unique_paths)

    # ── Apply ─────────────────────────────────────────────────────────────────
    cli.section("APPLYING")
    log_lines: list[str] = []
    ts = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    log_lines.append(f"{ts}  [runner]       START     Setup started")

    for mod in MODULES:
        cli.step(mod.name)
        try:
            mod.apply(state, rollback)
            state.applied_modules.append(mod.key)
            cli.done(mod.name)
            log_lines.append(
                f"{datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}  [{mod.key:<16}] APPLIED"
            )
        except Exception as exc:
            cli.error(f"{mod.name} failed: {exc}")
            state.errors.append(f"{mod.key}: {exc}")
            log_lines.append(
                f"{datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}  [{mod.key:<16}] ERROR     {exc}"
            )
            cli.warn("Rolling back all changes…")
            rollback.restore()
            cli.error("Changes have been rolled back. Project is in its original state.")
            _write_log(log_lines)
            return

    # ── Generate .env ─────────────────────────────────────────────────────────
    _generate_env(state, cli)
    log_lines.append(
        f"{datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}  [runner]       ENV       .env generated"
    )

    # ── Write log ─────────────────────────────────────────────────────────────
    log_lines.append(
        f"{datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}  [runner]       BACKUP    {rollback.backup_path()}"
    )
    log_lines.append(
        f"{datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}  [runner]       DONE      Setup complete"
    )
    _write_log(log_lines)

    # ── Done ──────────────────────────────────────────────────────────────────
    cli.section("DONE")
    cli.success(f"Project configured as \"{state.project_name}\"")
    cli.info(f"Backup saved to: {DIM}{rollback.backup_path()}{RESET}")
    cli.info("Next steps:")
    print(f"    {DIM}1.{RESET} Review .env and set any remaining values")
    if state.db_backend != "none":
        print(f"    {DIM}2.{RESET} flask db migrate -m \"initial schema\"")
        print(f"    {DIM}3.{RESET} flask db upgrade")
        print(f"    {DIM}4.{RESET} flask run")
    else:
        print(f"    {DIM}2.{RESET} flask run")
    print()

    # ── Optional self-cleanup ─────────────────────────────────────────────────
    if cli.confirm("Remove setup/ directory and setup.py now?", default=False):
        _self_destruct(cli)


def _show_env_summary(state: SetupState, cli: CLI) -> None:
    """Show what will be written to .env."""
    cli.info(f"Will generate .env with:")
    print(f"    {DIM}SECRET_KEY{RESET}   = <auto-generated {CYAN}secrets.token_hex(32){RESET}>")
    if state.db_backend != "none":
        print(f"    {DIM}DATABASE_URL{RESET} = {state.db_url_redacted()}")
    else:
        print(f"    {DIM}DATABASE_URL{RESET} = (empty)")


def _generate_env(state: SetupState, cli: CLI) -> None:
    """Write a fully populated .env file from the current state."""
    from setup.file_utils import env_set, read_file, write_file

    env_path = ROOT / ".env"

    # Start from .env.example if .env doesn't exist yet
    example = ROOT / ".env.example"
    if not env_path.exists() and example.exists():
        import shutil
        shutil.copy2(example, env_path)

    env_set(env_path, "FLASK_APP", "wsgi.py")
    env_set(env_path, "FLASK_ENV", "development")
    env_set(env_path, "SECRET_KEY", secrets.token_hex(32))
    env_set(env_path, "LOG_LEVEL", "INFO")
    env_set(env_path, "DATABASE_URL", state.db_url())

    cli.success(".env generated with a fresh SECRET_KEY")


def _write_log(lines: list[str]) -> None:
    log_path = ROOT / "setup.log"
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _self_destruct(cli: CLI) -> None:
    import atexit
    import os

    setup_pkg = ROOT / "setup"
    setup_py = ROOT / "setup.py"

    def _cleanup() -> None:
        try:
            shutil.rmtree(setup_pkg, ignore_errors=True)
            if setup_py.exists():
                os.remove(setup_py)
        except Exception:
            pass

    atexit.register(_cleanup)
    cli.success("setup/ and setup.py will be removed on exit.")
